// บันทึกไฟล์นี้ชื่อ questions.js
const questions = [
  // --- หมวดที่ 1: ความสามารถทั่วไป (30 ข้อ) ---
  { "id": 1, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 5, 10, 20, 40, ... ตัวเลขถัดไปคือข้อใด?", "options": ["60", "70", "80", "90"], "answerIndex": 2, "explanation": "\"ตอบ 80 เพราะเพิ่มขึ้นแบบคูณ 2 ครับ\"" },
  { "id": 2, "category": "ความสามารถทั่วไป", "question": "อุปมาอุปไมย: มีด : คม :: ? : ?", "options": ["เข็ม : แหลม", "ปืน : ดำ", "ไม้ : ยาว", "หิน : หนัก"], "answerIndex": 0, "explanation": "\"ตอบ เข็ม : แหลม เพราะเป็นคุณสมบัติเฉพาะตัวครับ\"" },
  { "id": 3, "category": "ความสามารถทั่วไป", "question": "ค่าเฉลี่ยของ 15, 25, 35, 45 คือเท่าใด?", "options": ["30", "32.5", "31", "25"], "answerIndex": 0, "explanation": "\"ตอบ 30 เพราะ (15+25+35+45)/4 = 30 ครับ\"" },
  { "id": 4, "category": "ความสามารถทั่วไป", "question": "ความเร็ว 80 กม./ชม. ในเวลา 3 ชม. จะได้ระยะทางเท่าใด?", "options": ["200", "240", "260", "280"], "answerIndex": 1, "explanation": "\"ตอบ 240 เพราะ 80 x 3 = 240 ครับ\"" },
  { "id": 5, "category": "ความสามารถทั่วไป", "question": "20% ของ 500 มีค่าเท่ากับข้อใด?", "options": ["50", "80", "100", "120"], "answerIndex": 2, "explanation": "\"ตอบ 100 เพราะ 0.20 x 500 = 100 ครับ\"" },
  { "id": 6, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 2, 5, 11, 23, ... ตัวเลขถัดไปคือข้อใด?", "options": ["45", "46", "47", "48"], "answerIndex": 2, "explanation": "\"ตอบ 47 เพราะ (ตัวหน้า x 2) + 1 ครับ\"" },
  { "id": 7, "category": "ความสามารถทั่วไป", "question": "ถ้าส้ม 3 กก. ราคา 120 บาท ส้ม 7 กก. จะราคาเท่าไหร่?", "options": ["240", "280", "300", "320"], "answerIndex": 1, "explanation": "\"ตอบ 280 เพราะกิโลละ 40 บาท 7 x 40 = 280 ครับ\"" },
  { "id": 8, "category": "ความสามารถทั่วไป", "question": "พื้นที่วงกลมรัศมี 7 ซม. มีค่าเท่าใด? (pi=22/7)", "options": ["44", "154", "196", "308"], "answerIndex": 1, "explanation": "\"ตอบ 154 จากสูตร 22/7 x 7 x 7 ครับ\"" },
  { "id": 9, "category": "ความสามารถทั่วไป", "question": "เลขชุดใดต่างจากพวก?", "options": ["2", "4", "6", "9"], "answerIndex": 3, "explanation": "\"ตอบ 9 เพราะเป็นเลขคี่ตัวเดียวครับ\"" },
  { "id": 10, "category": "ความสามารถทั่วไป", "question": "ซื้อเสื้อ 400 บาท ลด 15% ต้องจ่ายเงินกี่บาท?", "options": ["320", "340", "360", "380"], "answerIndex": 1, "explanation": "\"ตอบ 340 เพราะลดไป 60 บาทครับ\"" },
  { "id": 11, "category": "ความสามารถทั่วไป", "question": "ห.ร.ม. ของ 12 และ 18 คือข้อใด?", "options": ["2", "3", "6", "36"], "answerIndex": 2, "explanation": "\"ตอบ 6 เพราะหารลงตัวมากที่สุดครับ\"" },
  { "id": 12, "category": "ความสามารถทั่วไป", "question": "ค.ร.น. ของ 4 และ 6 คือข้อใด?", "options": ["10", "12", "24", "48"], "answerIndex": 1, "explanation": "\"ตอบ 12 เพราะน้อยที่สุดที่ทั้งสองหารลงตัวครับ\"" },
  { "id": 13, "category": "ความสามารถทั่วไป", "question": "มุมภายในของรูปสามเหลี่ยมรวมกันได้กี่องศา?", "options": ["90", "180", "270", "360"], "answerIndex": 1, "explanation": "\"ตอบ 180 องศาครับ\"" },
  { "id": 14, "category": "ความสามารถทั่วไป", "question": "เงิน 1,000 แบ่ง 2:3:5 คนได้มากสุดได้กี่บาท?", "options": ["200", "300", "500", "600"], "answerIndex": 2, "explanation": "\"ตอบ 500 เพราะ 5 ใน 10 ส่วนคือครึ่งหนึ่งครับ\"" },
  { "id": 15, "category": "ความสามารถทั่วไป", "question": "รากที่สองของ 625 คือเท่าใด?", "options": ["15", "25", "35", "45"], "answerIndex": 1, "explanation": "\"ตอบ 25 เพราะ 25x25 = 625 ครับ\"" },
  { "id": 16, "category": "ความสามารถทั่วไป", "question": "ทอดลูกเต๋า 1 ลูก โอกาสได้เลขคู่เป็นเท่าใด?", "options": ["1/2", "1/3", "1/6", "2/3"], "answerIndex": 0, "explanation": "\"ตอบ 1/2 เพราะเลขคู่มี 2,4,6 ครับ\"" },
  { "id": 17, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 1, 4, 9, 16, ... ตัวถัดไปคือ?", "options": ["20", "24", "25", "30"], "answerIndex": 2, "explanation": "\"ตอบ 25 เพราะเป็นเลขยกกำลังสองครับ\"" },
  { "id": 18, "category": "ความสามารถทั่วไป", "question": "เอสูงกว่าบี บีสูงกว่าซี ใครเตี้ยที่สุด?", "options": ["เอ", "บี", "ซี", "สรุปไม่ได้"], "answerIndex": 2, "explanation": "\"ตอบ ซี เพราะ เอ > บี > ซี ครับ\"" },
  { "id": 19, "category": "ความสามารถทั่วไป", "question": "วันนี้วันจันทร์ อีก 10 วันข้างหน้าคือวันอะไร?", "options": ["พุธ", "พฤหัสบดี", "ศุกร์", "เสาร์"], "answerIndex": 1, "explanation": "\"ตอบ พฤหัสบดี เพราะเศษจาก 7 คือ 3 วันครับ\"" },
  { "id": 20, "category": "ความสามารถทั่วไป", "question": "มุมฉากมีขนาดกี่องศา?", "options": ["45", "90", "180", "360"], "answerIndex": 1, "explanation": "\"ตอบ 90 องศาครับ\"" },
  { "id": 21, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 81, 27, 9, ... ตัวถัดไปคือ?", "options": ["1", "3", "4.5", "6"], "answerIndex": 1, "explanation": "\"ตอบ 3 เพราะหาร 3 ไปเรื่อยๆ ครับ\"" },
  { "id": 22, "category": "ความสามารถทั่วไป", "question": "ตากแดด : ร้อน :: ? : ?", "options": ["อาบน้ำ : หนาว", "กินข้าว : อิ่ม", "นอน : ฝัน", "เดิน : ไกล"], "answerIndex": 1, "explanation": "\"ตอบ กินข้าว : อิ่ม เป็นเหตุและผลครับ\"" },
  { "id": 23, "category": "ความสามารถทั่วไป", "question": "1-100 มีเลข 7 ทั้งหมดกี่ตัว?", "options": ["10", "11", "19", "20"], "answerIndex": 3, "explanation": "\"ตอบ 20 ตัว อย่าลืมนับช่วง 70-79 ครับ\"" },
  { "id": 24, "category": "ความสามารถทั่วไป", "question": "บอลแดง 3 ขาว 2 หยิบ 1 โอกาสได้แดงคือ?", "options": ["2/5", "3/5", "1/2", "3/2"], "answerIndex": 1, "explanation": "\"ตอบ 3/5 ครับ\"" },
  { "id": 25, "category": "ความสามารถทั่วไป", "question": "สี่เหลี่ยมกว้าง 5 ยาว 10 เส้นรอบรูปยาวเท่าใด?", "options": ["15", "30", "50", "60"], "answerIndex": 1, "explanation": "\"ตอบ 30 เพราะ (5+10) x 2 = 30 ครับ\"" },
  { "id": 26, "category": "ความสามารถทั่วไป", "question": "1,000 เมตร เท่ากับกี่กิโลเมตร?", "options": ["0.1", "1", "10", "100"], "answerIndex": 1, "explanation": "\"ตอบ 1 กม. ครับ\"" },
  { "id": 27, "category": "ความสามารถทั่วไป", "question": "อนุกรม: 1/2, 1/4, 1/8, ... ตัวถัดไปคือ?", "options": ["1/10", "1/12", "1/16", "1/20"], "answerIndex": 2, "explanation": "\"ตอบ 1/16 ครับ\"" },
  { "id": 28, "category": "ความสามารถทั่วไป", "question": "ถ้า X + 5 = 12 แล้ว 2X มีค่าเท่าไหร่?", "options": ["7", "14", "17", "24"], "answerIndex": 1, "explanation": "\"ตอบ 14 เพราะ X=7 ครับ\"" },
  { "id": 29, "category": "ความสามารถทั่วไป", "question": "จำนวนเฉพาะที่น้อยที่สุดคือเลขใด?", "options": ["0", "1", "2", "3"], "answerIndex": 2, "explanation": "\"ตอบ 2 ครับ\"" },
  { "id": 30, "category": "ความสามารถทั่วไป", "question": "0.5 คูณ 0.5 มีค่าเท่าใด?", "options": ["0.1", "0.25", "1.0", "2.5"], "answerIndex": 1, "explanation": "\"ตอบ 0.25 ครับ\"" },

  // --- หมวดที่ 2: ภาษาไทย (25 ข้อ) ---
  { "id": 31, "category": "ภาษาไทย", "question": "ข้อใดสะกดถูกต้องทุกคำ?", "options": ["สังเกตุ, อนุญาต", "สังเกต, อนุญาต", "สังเกตุ, อนุญาติ", "สังเกต, อนุญาติ"], "answerIndex": 1, "explanation": "\"ตอบ สังเกต และ อนุญาต ไม่มีสระอุครับ\"" },
  { "id": 32, "category": "ภาษาไทย", "question": "คำว่า 'กะทิ' ข้อใดเขียนถูกต้อง?", "options": ["กระทิ", "กะทิ", "กระธิ", "กะธิ"], "answerIndex": 1, "explanation": "\"ตอบ กะทิ ไม่มี ร เรือครับ\"" },
  { "id": 33, "category": "ภาษาไทย", "question": "ลักษณนามของ 'ช้างป่า' คือข้อใด?", "options": ["ตัว", "เชือก", "ตน", "ช้าง"], "answerIndex": 0, "explanation": "\"ตอบ ตัว ช้างป่าใช้ตัว ช้างบ้านใช้เชือกครับ\"" },
  { "id": 34, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำสมาส?", "options": ["ผลไม้", "ราชการ", "บ้านเรือน", "ไฟฟ้า"], "answerIndex": 1, "explanation": "\"ตอบ ราชการ มาจากภาษาบาลีสันสกฤตครับ\"" },
  { "id": 35, "category": "ภาษาไทย", "question": "สำนวน 'ชักใบให้เรือเสีย' หมายถึงอะไร?", "options": ["ทำงานเก่ง", "พูดนอกเรื่องทำให้เสียงาน", "ช่วยทำงาน", "ขยัน"], "answerIndex": 1, "explanation": "\"ตอบ พูดขวางๆ ให้เสียเรื่องครับ\"" },
  { "id": 36, "category": "ภาษาไทย", "question": "คำราชาศัพท์ของ 'กิน' สำหรับพระสงฆ์?", "options": ["เสวย", "ฉัน", "รับประทาน", "เสพ"], "answerIndex": 1, "explanation": "\"ตอบ ฉัน สำหรับพระสงฆ์ครับ\"" },
  { "id": 37, "category": "ภาษาไทย", "question": "ข้อใดเป็นประโยคความเดียว?", "options": ["แมวกินปลา", "เขาวิ่งและเดิน", "แม่บอกให้นอน", "พี่ไปน้องอยู่"], "answerIndex": 0, "explanation": "\"ตอบ แมวกินปลา มีกริยาเดียวครับ\"" },
  { "id": 38, "category": "ภาษาไทย", "question": "ข้อใดมาจากภาษาอังกฤษ?", "options": ["ก๋วยเตี๋ยว", "คอมพิวเตอร์", "ซาลาเปา", "มระกู"], "answerIndex": 1, "explanation": "\"ตอบ คอมพิวเตอร์ ครับ\"" },
  { "id": 39, "category": "ภาษาไทย", "question": "คำตรงข้ามของ 'ขยัน'?", "options": ["อดทน", "ประหยัด", "ขี้เกียจ", "ซื่อสัตย์"], "answerIndex": 2, "explanation": "\"ตอบ ขี้เกียจ ครับ\"" },
  { "id": 40, "category": "ภาษาไทย", "question": "คำว่า 'ศีรษะ' เขียนอย่างไรถูก?", "options": ["ศรีษะ", "ศีรษะ", "สีรษะ", "ศริษะ"], "answerIndex": 1, "explanation": "\"ตอบ ศีรษะ สระอีบน ศ ศาลาครับ\"" },
  { "id": 41, "category": "ภาษาไทย", "question": "ข้อใดใช้ 'รร' ผิด?", "options": ["กรรไกร", "บรรทัด", "พรรษา", "มารยาท"], "answerIndex": 3, "explanation": "\"ตอบ มารยาท ไม่ใช้ ร หันครับ\"" },
  { "id": 42, "category": "ภาษาไทย", "question": "ลักษณนามของ 'เลื่อย'?", "options": ["อัน", "เล่ม", "ปื้น", "ปาก"], "answerIndex": 2, "explanation": "\"ตอบ ปื้น ครับ\"" },
  { "id": 43, "category": "ภาษาไทย", "question": "คำว่า 'มงกุฎ' สะกดด้วยตัวอะไร?", "options": ["ด ชฎา", "ฏ ปฏัก", "ด เด็ก", "ต เต่า"], "answerIndex": 1, "explanation": "\"ตอบ ฏ ปฏัก (หัวหยัก) ครับ\"" },
  { "id": 44, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำอุทาน?", "options": ["สวัสดี", "ไชโย", "ขอบคุณ", "ลาก่อน"], "answerIndex": 1, "explanation": "\"ตอบ ไชโย แสดงความดีใจครับ\"" },
  { "id": 45, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำนาม?", "options": ["เดิน", "สวย", "โรงเรียน", "เร็ว"], "answerIndex": 2, "explanation": "\"ตอบ โรงเรียน เป็นสถานที่ครับ\"" },
  { "id": 46, "category": "ภาษาไทย", "question": "คำว่า 'พยายาม' มีกี่พยางค์?", "options": ["2", "3", "4", "5"], "answerIndex": 1, "explanation": "\"ตอบ 3 พยางค์ พะ-ยา-ยาม ครับ\"" },
  { "id": 47, "category": "ภาษาไทย", "question": "ความหมายของ 'ดาวค้างฟ้า'?", "options": ["ดาวตอนเช้า", "คนดังที่ยังดังอยู่", "ดาวตก", "เมฆ"], "answerIndex": 1, "explanation": "\"ตอบ คนที่มีชื่อเสียงนานครับ\"" },
  { "id": 48, "category": "ภาษาไทย", "question": "คำใช้เรียกกษัตริย์คือข้อใด?", "options": ["ราชาศัพท์", "สรรพนาม", "อสามานยนาม", "ราชาธิราช"], "answerIndex": 0, "explanation": "\"ตอบ ราชาศัพท์ ครับ\"" },
  { "id": 49, "category": "ภาษาไทย", "question": "ข้อใดควบกล้ำแท้?", "options": ["จริง", "เศร้า", "กวาด", "สร้อย"], "answerIndex": 2, "explanation": "\"ตอบ กวาด ออกเสียงควบกันครับ\"" },
  { "id": 50, "category": "ภาษาไทย", "question": "คำว่า 'ทรุดโทรม' อ่านอย่างไร?", "options": ["ทรุด-โทรม", "ซุด-โซม", "ทระ-อุด-โทรม", "สรง-โซม"], "answerIndex": 1, "explanation": "\"ตอบ ซุด-โซม ทร ออกเสียง ซ ครับ\"" },
  { "id": 51, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำพ้องรูป?", "options": ["เพลา", "กาล", "การณ์", "กาญจน์"], "answerIndex": 0, "explanation": "\"ตอบ เพลา อ่านได้ทั้ง เพ-ลา และ เพลา ครับ\"" },
  { "id": 52, "category": "ภาษาไทย", "question": "ตรงข้ามกับ 'มงคล'?", "options": ["โชคดี", "อัปมงคล", "สิริ", "รุ่งเรือง"], "answerIndex": 1, "explanation": "\"ตอบ อัปมงคล ครับ\"" },
  { "id": 53, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำประสม?", "options": ["พัดลม", "กะละมัง", "ทะลุ", "ตะปู"], "answerIndex": 0, "explanation": "\"ตอบ พัดลม (พัด+ลม) ครับ\"" },
  { "id": 54, "category": "ภาษาไทย", "question": "โวหารเปรียบเหมือน เรียกว่า?", "options": ["บรรยาย", "อุปมา", "สาธก", "เทศนา"], "answerIndex": 1, "explanation": "\"ตอบ อุปมาโวหาร ครับ\"" },
  { "id": 55, "category": "ภาษาไทย", "question": "ภาษาทางการที่ถูกต้องคือ?", "options": ["กินข้าว", "ทานข้าว", "รับประทานอาหาร", "ยัดบาตร"], "answerIndex": 2, "explanation": "\"ตอบ รับประทานอาหาร ครับ\"" },

  // --- หมวดที่ 3: ภาษาอังกฤษ (30 ข้อ) ---
  { "id": 56, "category": "ภาษาอังกฤษ", "question": "Plural of 'Child'?", "options": ["Childs", "Children", "Childrens", "Childes"], "answerIndex": 1, "explanation": "\"ตอบ Children เป็นพหูพจน์เปลี่ยนรูปครับ\"" },
  { "id": 57, "category": "ภาษาอังกฤษ", "question": "I _____ to the market yesterday.", "options": ["go", "goes", "went", "going"], "answerIndex": 2, "explanation": "\"ตอบ went กริยาช่อง 2 เพราะเป็นอดีตครับ\"" },
  { "id": 58, "category": "ภาษาอังกฤษ", "question": "She is _____ than her sister.", "options": ["tall", "taller", "tallest", "more tall"], "answerIndex": 1, "explanation": "\"ตอบ taller ขั้นกว่าครับ\"" },
  { "id": 59, "category": "ภาษาอังกฤษ", "question": "_____ do you live?", "options": ["What", "Where", "When", "Who"], "answerIndex": 1, "explanation": "\"ตอบ Where ถามที่อยู่ครับ\"" },
  { "id": 60, "category": "ภาษาอังกฤษ", "question": "There _____ an apple on the table.", "options": ["is", "am", "are", "be"], "answerIndex": 0, "explanation": "\"ตอบ is เพราะแอปเปิ้ลผลเดียวครับ\"" },
  { "id": 61, "category": "ภาษาอังกฤษ", "question": "Listen! The baby _____.", "options": ["cry", "cries", "is crying", "cried"], "answerIndex": 2, "explanation": "\"ตอบ is crying กำลังเกิดขึ้นครับ\"" },
  { "id": 62, "category": "ภาษาอังกฤษ", "question": "He has _____ orange.", "options": ["a", "an", "the", "some"], "answerIndex": 1, "explanation": "\"ตอบ an นำหน้าสระครับ\"" },
  { "id": 63, "category": "ภาษาอังกฤษ", "question": "They _____ football every Sunday.", "options": ["play", "plays", "playing", "played"], "answerIndex": 0, "explanation": "\"ตอบ play ปัจจุบันที่เป็นกิจวัตรครับ\"" },
  { "id": 64, "category": "ภาษาอังกฤษ", "question": "The sun _____ in the east.", "options": ["rise", "rises", "rising", "rose"], "answerIndex": 1, "explanation": "\"ตอบ rises ความจริงธรรมชาติครับ\"" },
  { "id": 65, "category": "ภาษาอังกฤษ", "question": "Can you help _____?", "options": ["I", "my", "me", "mine"], "answerIndex": 2, "explanation": "\"ตอบ me เป็นกรรมครับ\"" },
  { "id": 66, "category": "ภาษาอังกฤษ", "question": "Which one is a fruit?", "options": ["Cabbage", "Carrot", "Mango", "Potato"], "answerIndex": 2, "explanation": "\"ตอบ Mango ผลไม้ครับ\"" },
  { "id": 67, "category": "ภาษาอังกฤษ", "question": "I am interested _____ music.", "options": ["in", "on", "at", "with"], "answerIndex": 0, "explanation": "\"ตอบ in ใช้คู่กับ interested ครับ\"" },
  { "id": 68, "category": "ภาษาอังกฤษ", "question": "How _____ is this shirt?", "options": ["many", "much", "old", "far"], "answerIndex": 1, "explanation": "\"ตอบ much ถามราคาครับ\"" },
  { "id": 69, "category": "ภาษาอังกฤษ", "question": "You _____ smoke in the hospital.", "options": ["must", "mustn't", "can", "should"], "answerIndex": 1, "explanation": "\"ตอบ mustn't ต้องไม่ (ข้อห้าม) ครับ\"" },
  { "id": 70, "category": "ภาษาอังกฤษ", "question": "Yesterday was Monday. Today is _____.", "options": ["Tuesday", "Wednesday", "Thursday", "Friday"], "answerIndex": 0, "explanation": "\"ตอบ Tuesday ครับ\"" },
  { "id": 71, "category": "ภาษาอังกฤษ", "question": "The cat is _____ the chair.", "options": ["under", "between", "among", "behind of"], "answerIndex": 0, "explanation": "\"ตอบ under ใต้ครับ\"" },
  { "id": 72, "category": "ภาษาอังกฤษ", "question": "_____ is your name?", "options": ["What", "Who", "Whose", "Which"], "answerIndex": 0, "explanation": "\"ตอบ What ครับ\"" },
  { "id": 73, "category": "ภาษาอังกฤษ", "question": "We _____ to school by bus.", "options": ["goes", "go", "going", "gone"], "answerIndex": 1, "explanation": "\"ตอบ go ประธานพหูพจน์ครับ\"" },
  { "id": 74, "category": "ภาษาอังกฤษ", "question": "Would you like _____ water?", "options": ["a", "an", "some", "any"], "answerIndex": 2, "explanation": "\"ตอบ some ใช้ในการเสนอครับ\"" },
  { "id": 75, "category": "ภาษาอังกฤษ", "question": "He is the _____ student in class.", "options": ["good", "better", "best", "more good"], "answerIndex": 2, "explanation": "\"ตอบ best ขั้นสูงสุดครับ\"" },
  { "id": 76, "category": "ภาษาอังกฤษ", "question": "It is _____ today. (มีแดดออก)", "options": ["rainy", "sunny", "cloudy", "windy"], "answerIndex": 1, "explanation": "\"ตอบ sunny ครับ\"" },
  { "id": 77, "category": "ภาษาอังกฤษ", "question": "Who catches criminals?", "options": ["Doctor", "Teacher", "Police officer", "Singer"], "answerIndex": 2, "explanation": "\"ตอบ Police officer ตำรวจครับ\"" },
  { "id": 78, "category": "ภาษาอังกฤษ", "question": "I don't have _____ money.", "options": ["some", "any", "a", "many"], "answerIndex": 1, "explanation": "\"ตอบ any ในประโยคปฏิเสธครับ\"" },
  { "id": 79, "category": "ภาษาอังกฤษ", "question": "Do you like coffee? - Yes, I _____.", "options": ["do", "does", "am", "like"], "answerIndex": 0, "explanation": "\"ตอบ do ถาม Do ตอบ do ครับ\"" },
  { "id": 80, "category": "ภาษาอังกฤษ", "question": "Opposite of 'Big'?", "options": ["Large", "Small", "Huge", "Long"], "answerIndex": 1, "explanation": "\"ตอบ Small ครับ\"" },
  { "id": 81, "category": "ภาษาอังกฤษ", "question": "_____ are you today? - I'm fine.", "options": ["What", "How", "Who", "Where"], "answerIndex": 1, "explanation": "\"ตอบ How are you? ครับ\"" },
  { "id": 82, "category": "ภาษาอังกฤษ", "question": "She _____ a car last month.", "options": ["buy", "buys", "bought", "buying"], "answerIndex": 2, "explanation": "\"ตอบ bought ช่อง 2 ครับ\"" },
  { "id": 83, "category": "ภาษาอังกฤษ", "question": "Please _____ the door.", "options": ["open", "opens", "opening", "opened"], "answerIndex": 0, "explanation": "\"ตอบ open ครับ\"" },
  { "id": 84, "category": "ภาษาอังกฤษ", "question": "I have been here _____ 2 hours.", "options": ["since", "for", "at", "in"], "answerIndex": 1, "explanation": "\"ตอบ for บอกระยะเวลาครับ\"" },
  { "id": 85, "category": "ภาษาอังกฤษ", "question": "This is _____ house. (ของพวกเขา)", "options": ["their", "they", "them", "theirs"], "answerIndex": 0, "explanation": "\"ตอบ their ครับ\"" },

  // --- หมวดที่ 4: เทคโนโลยีสารสนเทศ (25 ข้อ) ---
  { "id": 86, "category": "เทคโนโลยีสารสนเทศ", "question": "RAM ย่อมาจากอะไร?", "options": ["Read Access Memory", "Random Access Memory", "Ready Memory", "Run Memory"], "answerIndex": 1, "explanation": "\"ตอบ Random Access Memory ครับ\"" },
  { "id": 87, "category": "เทคโนโลยีสารสนเทศ", "question": "อุปกรณ์ใดเป็นทั้ง Input และ Output?", "options": ["Keyboard", "Mouse", "Touch Screen", "Printer"], "answerIndex": 2, "explanation": "\"ตอบ Touch Screen ครับ\"" },
  { "id": 88, "category": "เทคโนโลยีสารสนเทศ", "question": "Ctrl + V คืออะไร?", "options": ["Copy", "Cut", "Paste", "Save"], "answerIndex": 2, "explanation": "\"ตอบ Paste (วาง) ครับ\"" },
  { "id": 89, "category": "เทคโนโลยีสารสนเทศ", "question": ".go.th คือหน่วยงานใด?", "options": ["โรงเรียน", "เอกชน", "รัฐบาล", "มูลนิธิ"], "answerIndex": 2, "explanation": "\"ตอบ รัฐบาล ครับ\"" },
  { "id": 90, "category": "เทคโนโลยีสารสนเทศ", "question": "ใช้ท่องเน็ตคือซอฟต์แวร์ใด?", "options": ["Web Browser", "OS", "Database", "Word"], "answerIndex": 0, "explanation": "\"ตอบ Web Browser ครับ\"" },
  { "id": 91, "category": "เทคโนโลยีสารสนเทศ", "question": "ข้อใดคือระบบปฏิบัติการ?", "options": ["Office", "Windows 11", "Chrome", "Photoshop"], "answerIndex": 1, "explanation": "\"ตอบ Windows 11 ครับ\"" },
  { "id": 92, "category": "เทคโนโลยีสารสนเทศ", "question": "Phishing คืออะไร?", "options": ["พังเครื่อง", "หลอกเอาข้อมูล", "เพิ่มความเร็ว", "ซ่อมไฟล์"], "answerIndex": 1, "explanation": "\"ตอบ หลอกเอาข้อมูลส่วนตัวครับ\"" },
  { "id": 93, "category": "เทคโนโลยีสารสนเทศ", "question": "CPU เปรียบกับอวัยวะใด?", "options": ["หัวใจ", "ปอด", "สมอง", "มือ"], "answerIndex": 2, "explanation": "\"ตอบ สมอง ประมวลผลครับ\"" },
  { "id": 94, "category": "เทคโนโลยีสารสนเทศ", "question": "1 GB ประมาณกี่ MB?", "options": ["10", "100", "1,000", "10,000"], "answerIndex": 2, "explanation": "\"ตอบ 1,000 MB ครับ\"" },
  { "id": 95, "category": "เทคโนโลยีสารสนเทศ", "question": "Wi-Fi เป็นการเชื่อมต่อแบบใด?", "options": ["มีสาย", "ไร้สาย", "ดาวเทียม", "สายโทรศัพท์"], "answerIndex": 1, "explanation": "\"ตอบ ไร้สาย ครับ\"" },
  { "id": 96, "category": "เทคโนโลยีสารสนเทศ", "question": "ข้อใดเป็น Hardware?", "options": ["Windows", "Excel", "Mouse", "Antivirus"], "answerIndex": 2, "explanation": "\"ตอบ Mouse จับต้องได้ครับ\"" },
  { "id": 97, "category": "เทคโนโลยีสารสนเทศ", "question": ".pdf ย่อมาจากอะไร?", "options": ["Personal", "Portable Document Format", "Print", "Public"], "answerIndex": 1, "explanation": "\"ตอบ Portable Document Format ครับ\"" },
  { "id": 98, "category": "เทคโนโลยีสารสนเทศ", "question": "Social ใดเน้นข้อความสั้น?", "options": ["X (Twitter)", "Facebook", "Instagram", "Pinterest"], "answerIndex": 0, "explanation": "\"ตอบ X ครับ\"" },
  { "id": 99, "category": "เทคโนโลยีสารสนเทศ", "question": "Cloud Storage คืออะไร?", "options": ["ก้อนเมฆ", "ฝากไฟล์บนเน็ต", "พ่นควัน", "ระบายร้อน"], "answerIndex": 1, "explanation": "\"ตอบ ฝากไฟล์บนเซิร์ฟเวอร์ออนไลน์ครับ\"" },
  { "id": 100, "category": "เทคโนโลยีสารสนเทศ", "question": "Network Administrator คือใคร?", "options": ["คนเล่นเน็ต", "ผู้ดูแลระบบเครือข่าย", "คนเขียนโปรแกรม", "คนซ่อมจอ"], "answerIndex": 1, "explanation": "\"ตอบ ผู้ดูแลระบบเครือข่ายครับ\"" },
  { "id": 101, "category": "เทคโนโลยีสารสนเทศ", "question": "ผิด พ.ร.บ.คอมพิวเตอร์ คือข้อใด?", "options": ["กด Like", "โพสต์ด่าผู้อื่น", "ส่งเมลงาน", "ใช้ Google"], "answerIndex": 1, "explanation": "\"ตอบ โพสต์ด่าทำให้เสียหายครับ\"" },
  { "id": 102, "category": "เทคโนโลยีสารสนเทศ", "question": "URL คืออะไร?", "options": ["เจ้าของเว็บ", "ที่อยู่เว็บไซต์", "ความเร็วเน็ต", "รหัสเครื่อง"], "answerIndex": 1, "explanation": "\"ตอบ ที่อยู่เว็บไซต์ ครับ\"" },
  { "id": 103, "category": "เทคโนโลยีสารสนเทศ", "question": "ไวรัสเรียกค่าไถ่คือ?", "options": ["Worm", "Trojan", "Ransomware", "Spyware"], "answerIndex": 2, "explanation": "\"ตอบ Ransomware ครับ\"" },
  { "id": 104, "category": "เทคโนโลยีสารสนเทศ", "question": "E-mail ย่อมาจาก?", "options": ["Easy", "Electronic Mail", "Electric", "Express"], "answerIndex": 1, "explanation": "\"ตอบ Electronic Mail ครับ\"" },
  { "id": 105, "category": "เทคโนโลยีสารสนเทศ", "question": "อุปกรณ์สำรองไฟคือ?", "options": ["CPU", "UPS", "USB", "GPU"], "answerIndex": 1, "explanation": "\"ตอบ UPS ครับ\"" },
  { "id": 106, "category": "เทคโนโลยีสารสนเทศ", "question": "Log out สำคัญอย่างไร?", "options": ["เน็ตเร็ว", "ความปลอดภัยบัญชี", "ประหยัดแบต", "เพิ่มพื้นที่"], "answerIndex": 1, "explanation": "\"ตอบ เพื่อความปลอดภัยครับ\"" },
  { "id": 107, "category": "เทคโนโลยีสารสนเทศ", "question": "F5 ทำหน้าที่ใด?", "options": ["ปิดเครื่อง", "ลบไฟล์", "Refresh", "Print"], "answerIndex": 2, "explanation": "\"ตอบ Refresh หน้าเว็บครับ\"" },
  { "id": 108, "category": "เทคโนโลยีสารสนเทศ", "question": "AI ย่อมาจาก?", "options": ["Auto", "Artificial Intelligence", "Actual", "Apple"], "answerIndex": 1, "explanation": "\"ตอบ ปัญญาประดิษฐ์ ครับ\"" },
  { "id": 109, "category": "เทคโนโลยีสารสนเทศ", "question": "Spam คืออะไร?", "options": ["ไวรัส", "ขยะอิเล็กทรอนิกส์", "รหัสยาก", "อัปเกรด"], "answerIndex": 1, "explanation": "\"ตอบ เมลขยะที่น่ารำคาญครับ\"" },
  { "id": 110, "category": "เทคโนโลยีสารสนเทศ", "question": "คอมค้างบ่อยควรเช็กอะไร?", "options": ["จอ", "ความร้อน/ไวรัส", "เมาส์", "โต๊ะ"], "answerIndex": 1, "explanation": "\"ตอบ ความร้อนและไวรัสเป็นสาเหตุหลักครับ\"" },

  // --- หมวดที่ 5: กฎหมายที่ประชาชนควรรู้ (20 ข้อ) ---
  { "id": 111, "category": "กฎหมาย", "question": "หมั้นได้เมื่ออายุเท่าใด?", "options": ["15", "17", "18", "20"], "answerIndex": 1, "explanation": "\"ตอบ 17 ปีบริบูรณ์ครับ\"" },
  { "id": 112, "category": "กฎหมาย", "question": "แจ้งเกิดภายในกี่วัน?", "options": ["7", "15", "30", "24 ชม."], "answerIndex": 1, "explanation": "\"ตอบ 15 วันครับ\"" },
  { "id": 113, "category": "กฎหมาย", "question": "บรรลุนิติภาวะเมื่อใด?", "options": ["18", "20 หรือสมรสถูกกฎหมาย", "จบปริญญา", "มีงาน"], "answerIndex": 1, "explanation": "\"ตอบ 20 ปี หรือสมรสครับ\"" },
  { "id": 114, "category": "กฎหมาย", "question": "ดอกเบี้ยเงินกู้ห้ามเกินร้อยละเท่าใด?", "options": ["10", "15", "20", "25"], "answerIndex": 1, "explanation": "\"ตอบ 15% ต่อปีครับ\"" },
  { "id": 115, "category": "กฎหมาย", "question": "แจ้งตายภายในกี่ชั่วโมง?", "options": ["12", "24", "48", "72"], "answerIndex": 1, "explanation": "\"ตอบ 24 ชั่วโมงครับ\"" },
  { "id": 116, "category": "กฎหมาย", "question": "มรดกตกทอดเมื่อใด?", "options": ["ป่วย", "ตาย", "สั่งไว้", "ร้องขอ"], "answerIndex": 1, "explanation": "\"ตอบ เมื่อตายทันทีครับ\"" },
  { "id": 117, "category": "กฎหมาย", "question": "ลักทรัพย์กลางคืนโทษเป็นอย่างไร?", "options": ["เบา", "ปกติ", "หนักกว่าปกติ", "ไม่มี"], "answerIndex": 2, "explanation": "\"ตอบ หนักกว่าปกติครับ\"" },
  { "id": 118, "category": "กฎหมาย", "question": "บัตรประชาชนอายุกี่ปี?", "options": ["5", "8", "10", "ตลอดชีพ"], "answerIndex": 1, "explanation": "\"ตอบ 8 ปีครับ\"" },
  { "id": 119, "category": "กฎหมาย", "question": "แจ้งย้ายที่อยู่ภายในกี่วัน?", "options": ["7", "15", "30", "60"], "answerIndex": 1, "explanation": "\"ตอบ 15 วันครับ\"" },
  { "id": 120, "category": "กฎหมาย", "question": "พบศพต้องแจ้งภายในกี่ชั่วโมง?", "options": ["12", "24", "48", "ทันที"], "answerIndex": 1, "explanation": "\"ตอบ 24 ชั่วโมงครับ\"" },
  { "id": 121, "category": "กฎหมาย", "question": "กฎหมายเทศบาลเรียกว่า?", "options": ["พ.ร.บ.", "เทศบัญญัติ", "กฎกระทรวง", "พระราชกฤษฎีกา"], "answerIndex": 1, "explanation": "\"ตอบ เทศบัญญัติ ครับ\"" },
  { "id": 122, "category": "กฎหมาย", "question": "พินัยกรรมเขียนเองต้องมีพยานกี่คน?", "options": ["ไม่ต้องมี", "1", "2", "3"], "answerIndex": 0, "explanation": "\"ตอบ ไม่ต้องมีถ้าเขียนเองทั้งฉบับครับ\"" },
  { "id": 123, "category": "กฎหมาย", "question": "อายุความฆ่าคนตายกี่ปี?", "options": ["10", "15", "20", "ไม่มี"], "answerIndex": 2, "explanation": "\"ตอบ 20 ปีครับ\"" },
  { "id": 124, "category": "กฎหมาย", "question": "ศาลชั้นต้นตัดสินคดีทั่วไปคือ?", "options": ["ศาลแขวง/จังหวัด", "อุทธรณ์", "ฎีกา", "รัฐธรรมนูญ"], "answerIndex": 0, "explanation": "\"ตอบ ศาลแขวง หรือ ศาลจังหวัด ครับ\"" },
  { "id": 125, "category": "กฎหมาย", "question": "ดูหมิ่นเจ้าพนักงานโทษเป็นอย่างไร?", "options": ["ปรับ", "จำ/ปรับ", "ไม่ผิด", "ตักเตือน"], "answerIndex": 1, "explanation": "\"ตอบ มีทั้งจำและปรับครับ\"" },
  { "id": 126, "category": "กฎหมาย", "question": "ความผิดใดยอมความได้?", "options": ["ฆ่าคน", "ปล้น", "หมิ่นประมาท", "ทำร้ายสาหัส"], "answerIndex": 2, "explanation": "\"ตอบ หมิ่นประมาท ครับ\"" },
  { "id": 127, "category": "กฎหมาย", "question": "ลงบัญชีทหารเมื่ออายุเท่าใด?", "options": ["15", "17", "20", "21"], "answerIndex": 1, "explanation": "\"ตอบ 17 ปีครับ\"" },
  { "id": 128, "category": "กฎหมาย", "question": "นิติกรรมที่โดนข่มขู่เป็นอย่างไร?", "options": ["สมบูรณ์", "โมฆะ", "โมฆียะ", "ใช้ไม่ได้"], "answerIndex": 2, "explanation": "\"ตอบ โมฆียะ บอกล้างได้ครับ\"" },
  { "id": 129, "category": "กฎหมาย", "question": "ตำรวจคุมตัวได้ไม่เกินกี่ชั่วโมง?", "options": ["24", "48", "72", "7 วัน"], "answerIndex": 1, "explanation": "\"ตอบ 48 ชั่วโมงครับ\"" },
  { "id": 130, "category": "กฎหมาย", "question": "พยานที่เห็นเองเรียกว่า?", "options": ["บอกเล่า", "เอกสาร", "ประจักษ์พยาน", "แวดล้อม"], "answerIndex": 2, "explanation": "\"ตอบ ประจักษ์พยาน ครับ\"" },

  // --- หมวดที่ 6: สังคม วัฒนธรรม อาเซียน (20 ข้อ) ---
  { "id": 131, "category": "สังคม", "question": "สงฆ์ 1,250 รูป ประชุมวันใด?", "options": ["มาฆบูชา", "วิสาขบูชา", "อาสาฬหบูชา", "เข้าพรรษา"], "answerIndex": 0, "explanation": "\"ตอบ วันมาฆบูชา ครับ\"" },
  { "id": 132, "category": "สังคม", "question": "เศรษฐกิจพอเพียงกี่ห่วงกี่เงื่อนไข?", "options": ["2/2", "3/2", "3/3", "4/2"], "answerIndex": 1, "explanation": "\"ตอบ 3 ห่วง 2 เงื่อนไข ครับ\"" },
  { "id": 133, "category": "สังคม", "question": "วัฒนธรรมมีกี่ประเภท?", "options": ["2", "3", "4", "5"], "answerIndex": 2, "explanation": "\"ตอบ 4 ประเภท (คติ, เนติ, สห, วัตถุ) ครับ\"" },
  { "id": 134, "category": "สังคม", "question": "ตักบาตรเทโววันใด?", "options": ["มาฆะ", "วิสาขะ", "ออกพรรษา", "สงกรานต์"], "answerIndex": 2, "explanation": "\"ตอบ ออกพรรษา ครับ\"" },
  { "id": 135, "category": "สังคม", "question": "จริยธรรมคืออะไร?", "options": ["สิ่งที่ควรทำ", "ลงโทษ", "กฎหมาย", "ฐานะ"], "answerIndex": 0, "explanation": "\"ตอบ สิ่งที่ควรประพฤติดีงามครับ\"" },
  { "id": 136, "category": "สังคม", "question": "สีน้ำเงินในธงไตรรงค์คือ?", "options": ["ชาติ", "ศาสนา", "กษัตริย์", "ประชาชน"], "answerIndex": 2, "explanation": "\"ตอบ พระมหากษัตริย์ ครับ\"" },
  { "id": 137, "category": "สังคม", "question": "ค่านิยม 12 ประการ ข้อแรกคือ?", "options": ["กตัญญู", "รักชาติ ศาสน์ กษัตริย์", "มีศีล", "ขยัน"], "answerIndex": 1, "explanation": "\"ตอบ รักชาติ ศาสนา พระมหากษัตริย์ ครับ\"" },
  { "id": 138, "category": "สังคม", "question": "ประเพณีภาคอีสานคือ?", "options": ["ชักพระ", "ไหลเรือไฟ", "ตักบาตรดอกไม้", "อุ้มพระดำน้ำ"], "answerIndex": 1, "explanation": "\"ตอบ ไหลเรือไฟ ครับ\"" },
  { "id": 139, "category": "สังคม", "question": "เบญจศีลข้อ 3 ห้ามเรื่องใด?", "options": ["ฆ่า", "ลักทรัพย์", "กาม", "มุสา"], "answerIndex": 2, "explanation": "\"ตอบ กาเมสุมิจฉาจาราฯ ครับ\"" },
  { "id": 140, "category": "สังคม", "question": "ใครพระราชทานเศรษฐกิจพอเพียง?", "options": ["ร.5", "ร.7", "ร.9", "ร.10"], "answerIndex": 2, "explanation": "\"ตอบ ในหลวงรัชกาลที่ 9 ครับ\"" },
  { "id": 141, "category": "อาเซียน", "question": "สำนักงานเลขาธิการอาเซียนอยู่ที่ใด?", "options": ["กรุงเทพ", "สิงคโปร์", "จาการ์ตา", "กัวลาลัมเปอร์"], "answerIndex": 2, "explanation": "\"ตอบ จาการ์ตา อินโดนีเซียครับ\"" },
  { "id": 142, "category": "อาเซียน", "question": "คำขวัญอาเซียนคือ?", "options": ["One Vision...", "Unity", "Better Life", "Stronger"], "answerIndex": 0, "explanation": "\"ตอบ One Vision, One Identity, One Community ครับ\"" },
  { "id": 143, "category": "อาเซียน", "question": "สมาชิกลำดับที่ 11 คือ?", "options": ["เมียนมา", "กัมพูชา", "ติมอร์-เลสเต", "ลาว"], "answerIndex": 2, "explanation": "\"ตอบ ติมอร์-เลสเต ครับ\"" },
  { "id": 144, "category": "อาเซียน", "question": "ดอกไม้ประจำชาติไทยคือ?", "options": ["กุหลาบ", "ราชพฤกษ์", "ชบา", "ลำดวน"], "answerIndex": 1, "explanation": "\"ตอบ ราชพฤกษ์ (คูน) ครับ\"" },
  { "id": 145, "category": "อาเซียน", "question": "ข้อใดไม่ใช่ 3 เสาหลักอาเซียน?", "options": ["การเมือง", "เศรษฐกิจ", "การศึกษา", "สังคม"], "answerIndex": 2, "explanation": "\"ตอบ การศึกษา รวมอยู่ในเสาสังคมฯ ครับ\"" },
  { "id": 146, "category": "อาเซียน", "question": "วันอาเซียนคือวันใด?", "options": ["1 ม.ค.", "13 เม.ย.", "8 ส.ค.", "5 ธ.ค."], "answerIndex": 2, "explanation": "\"ตอบ 8 สิงหาคม ครับ\"" },
  { "id": 147, "category": "อาเซียน", "question": "เพลงอาเซียนคือเพลงใด?", "options": ["ASEAN Way", "ASEAN Song", "Unity", "Freedom"], "answerIndex": 0, "explanation": "\"ตอบ The ASEAN Way ครับ\"" },
  { "id": 148, "category": "อาเซียน", "question": "ประเทศใดไม่อยู่ในอาเซียน?", "options": ["ลาว", "เวียดนาม", "เกาหลีใต้", "ฟิลิปปินส์"], "answerIndex": 2, "explanation": "\"ตอบ เกาหลีใต้ ครับ\"" },
  { "id": 149, "category": "อาเซียน", "question": "เงินของลาวคือ?", "options": ["ดอลลาร์", "จ๊าด", "กีบ", "เรียล"], "answerIndex": 2, "explanation": "\"ตอบ กีบ ครับ\"" },
  { "id": 150, "category": "อาเซียน", "question": "สัตว์ประจำชาติอินโดนีเซียคือ?", "options": ["ช้าง", "เสือ", "มังกรโคโมโด", "สิงโต"], "answerIndex": 2, "explanation": "\"ตอบ มังกรโคโมโด ครับ\"" }
];
